In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Data Structure:[resturant_id,2021,2022,2023,2024]
sales_data =np.array([
    [1,150000,180000,220000,250000],    #Sundar Biryani House
    [2,120000,140000,160000,190000],    #Beijing Bites
    [3,200000,230000,260000,300000],    #Pizza Hub
    [4,180000,210000,240000,270000],    #Burger point 
    [5,160000,185000,205000,230000]     #Coffee Shop
])

In [3]:
print("=== Zomato sales analysis ===")

=== Zomato sales analysis ===


In [4]:
print("\n Sales data shape",sales_data.shape)
print("\n Sample data for 1st 3 retau :",sales_data[:, 1:])



 Sales data shape (5, 5)

 Sample data for 1st 3 retau : [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


In [5]:
#Minimum sales per resturaant
min_sales = np.min(sales_data[:,1:],axis=1)
print(min_sales)

[150000 120000 200000 180000 160000]


In [6]:
#Maximum sales per resturaant
max_sales = np.max(sales_data[:,1:],axis=0)
print(max_sales)

[200000 230000 260000 300000]


In [7]:
#Average sales per resturaant
avg_sales = np.mean(sales_data[:,1:],axis=1)
print(avg_sales)

[200000. 152500. 247500. 225000. 195000.]


In [8]:
cumsum = np.cumsum(sales_data[:,1:],axis=1)
print(cumsum)

[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


In [9]:
resturant_type =np.array(['biryani','chinese','pizza','burger','cafe'])
vectorized_upper = np.vectorize(str.upper)
print("Vectorized Upper",vectorized_upper(resturant_type))
monthly_avg =sales_data[:,1:] / 12
print(monthly_avg)

Vectorized Upper ['BIRYANI' 'CHINESE' 'PIZZA' 'BURGER' 'CAFE']
[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
