# **2D Array**

In [5]:
import numpy as np

In [1]:
k=[[1,2,3],[4,5,6],[9,8,7]]

In [7]:
arr=np.array(k)

In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7]])

In [9]:
arr.sum(axis=0)

array([14, 15, 16])

In [10]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [11]:
arr.T

array([[1, 4, 9],
       [2, 5, 8],
       [3, 6, 7]])

In [12]:
arr.flat

In [14]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
9
8
7


In [15]:
arr.ndim

2

In [16]:
arr.size

9

In [21]:
arr.nbytes

36

In [22]:
one=np.array([177,2,9,1,0])

In [23]:
one.argmax()

0

In [25]:
one.argmin()

4

In [26]:
one.argsort()

array([4, 3, 1, 2, 0], dtype=int64)

In [27]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7]])

In [28]:
arr.argmin()

0

In [30]:
arr.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [32]:
arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [33]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [34]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 9, 8, 7])

In [37]:
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [9],
       [8],
       [7]])

In [38]:
k

[[1, 2, 3], [4, 5, 6], [9, 8, 7]]

In [39]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7]])

In [40]:
arr2=np.array([[4,7,9],[3,8,9],[1,3,6]])

In [41]:
arr2

array([[4, 7, 9],
       [3, 8, 9],
       [1, 3, 6]])

In [42]:
arr+arr2

array([[ 5,  9, 12],
       [ 7, 13, 15],
       [10, 11, 13]])

In [43]:
arr*arr2

array([[ 4, 14, 27],
       [12, 40, 54],
       [ 9, 24, 42]])

In [44]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [3.        , 2.82842712, 2.64575131]])

In [45]:
arr.sum()

45

In [46]:
arr.max()

9

In [47]:
np.where(arr>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))