In [2]:
import numpy as np

In [4]:
a= np.array([1,2,3,4,5])

In [6]:
b=np.array([1,6,3,4,9])

In [7]:
print(a)

[1 2 3 4 5]


In [8]:
print(b)

[1 6 3 4 9]


In [10]:
type(a)

numpy.ndarray

In [11]:
type(b)

numpy.ndarray

In [12]:
a.dtype

dtype('int32')

In [13]:
a.ndim

1

In [14]:
k=np.array([[1,3,6]])

In [15]:
k.ndim

2

In [17]:
k[0,1]

3

In [18]:
k.shape

(1, 3)

In [19]:
k.dtype

dtype('int32')

In [20]:
k

array([[1, 3, 6]])

In [21]:
k[0,0]=8

In [22]:
k

array([[8, 3, 6]])

# **Array Creation : Conversion from other python structure**

In [25]:
listArray=np.array([[8,3,6],[1,6,9],[3,5,4]])

In [26]:
listArray

array([[8, 3, 6],
       [1, 6, 9],
       [3, 5, 4]])

In [29]:
listArray.shape

(3, 3)

In [30]:
listArray.size

9

In [32]:
z=np.zeros((2,3))

In [33]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
r=np.arange(7)

In [35]:
r

array([0, 1, 2, 3, 4, 5, 6])

In [36]:
s=np.linspace(1,50,10)

In [37]:
s

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [42]:
s1=np.linspace(1,16,5)

In [43]:
s1

array([ 1.  ,  4.75,  8.5 , 12.25, 16.  ])

In [46]:
e=np.empty((5,5))

In [47]:
e

array([[6.23042070e-307, 1.42417221e-306, 1.60219306e-306,
        7.56593017e-307, 7.56587584e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.42417221e-306, 7.56593017e-307,
        1.37961302e-306, 1.11259940e-306],
       [1.60219035e-306, 1.33511018e-306, 8.90092016e-307,
        9.79098366e-307, 9.34605037e-307],
       [1.37962320e-306, 1.37961302e-306, 2.22522596e-306,
        0.00000000e+000, 0.00000000e+000]])

In [48]:
like=np.empty_like(s)

In [49]:
like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [51]:
ide=np.identity(33)

In [52]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [53]:
ide.shape

(33, 33)

In [54]:
arr= np.arange(99)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [57]:
arr=arr.reshape(3,33)

In [58]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

**To convert it into Real shape**

In [59]:
arr=arr.ravel()

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [62]:
arr.shape

(99,)