In [2]:
import numpy as np

arr = np.array([10,20,30,40,50,60])
print(arr)
new_arr =np.delete(arr,0)
print(new_arr)

[10 20 30 40 50 60]
[20 30 40 50 60]


In [5]:
arr_2d = np.array([[1,2,3],[4,5,6]])

new_arr_2d = np.delete(arr_2d,0,axis=0)
print(new_arr_2d)

[[4 5 6]]


In [7]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [10]:
arr3 = np.array([1,2,np.nan,4,np.nan,6])
print(np.isnan(arr))

print(np.nan == np.nan)

[False False False False False False]
False
